### PR TITLE
User profile: events list - add day of the week to date string

### PR DESCRIPTION
**Pull request by victor-kotov-arcadia**
short day name ahead of date at event details

### CODE REVIEW

**Comment by DesmanLead** [comment]
Is the same pattern used on profile screen? As far as I remember there are separate screens: employee details and profile.

**Comment by victor-kotov-arcadia** [comment]
> Is the same pattern used on profile screen? As far as I remember there are separate screens: employee details and profile.

Yes, that was my assumption too, but from my tests it seems to be fine now - I've checked my profile and also checked it via Company->My details - both were showing it with week day.

**Comment by victor-kotov-arcadia** [comment]
> Don't we want such behaviour also in dialogs like "Your sick leave start on ..."?

Probably yes, but it wasn't mentioned in initial request

**Pull request merged**
